#!/usr/bin/env python3
"""Build the web app (web/) from the desktop app's screens.

The web version shows exactly the same screens as the desktop app, so the
desktop repo stays the one place they are edited. This script copies them
here and makes the few changes a browser needs:

  - web-shim.js (from web-src/) is loaded first - it provides
    require('electron') in the browser (see that file);
  - summary.html and index.html load KaTeX from /app/vendor/katex instead of
    node_modules (index.html: for math.js, the formulas on every screen).

Usage (from the server repo, with the desktop repo next to it):
    python3 tools/sync-web.py [../mindsync]

Run it again whenever the desktop screens change, then commit web/.
Don't edit files in web/ by hand - the next sync overwrites them.
"""
import pathlib
import re
import shutil
import sys

SERVER = pathlib.Path(__file__).resolve().parent.parent
CLIENT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else SERVER.parent / 'mindsync').resolve()
OUT = SERVER / 'web'
SRC = SERVER / 'web-src'

COPY = [
    'index.html', 'summary.html',
    'renderer.js', 'summary.js', 'math.js', 'ui.js', 'icons.js', 'i18n.js', 'i18n-he.js',
    'tokens.css', 'themes.css', 'ui-kit.css', 'styles.css', 'design.css',
]
OPTIONAL = ['assets', 'icon.png', 'favicon.ico']

SHIM_TAG = '<script src="web-shim.js"></script>'
HEADER = '<!-- Generated by tools/sync-web.py from the desktop app - edit it there, not here. -->'


def fail(msg):
    sys.exit(f'sync-web: {msg}')


def read(p):
    # newline='' keeps the file's own line endings (index.html is CRLF).
    with open(p, encoding='utf-8', newline='') as f:
        return f.read()


def write(p, text):
    with open(p, 'w', encoding='utf-8', newline='') as f:
        f.write(text)


def add_shim(html, name):
    """web-shim.js must run before any other script."""
    m = re.search(r'<script\b', html)
    if not m:
        fail(f'{name}: no <script> tag found')
    nl = '\r\n' if '\r\n' in html else '\n'
    indent = re.search(r'([ \t]*)$', html[:m.start()]).group(1)
    return html[:m.start()] + SHIM_TAG + nl + indent + html[m.start():]


ICON_HEAD = '''<link rel="icon" href="/favicon.ico" sizes="any">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <meta name="theme-color" content="#2f64d6">'''
WEB_HEAD = ICON_HEAD + '''
    <link rel="manifest" href="/manifest.webmanifest">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="MindSync">
    <meta name="description" content="MindSync - study assistant for university students. עוזר למידה לסטודנטים.">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="MindSync">
    <meta property="og:title" content="MindSync - עוזר למידה לסטודנטים">
    <meta property="og:description" content="שאלות תרגול מהקבצים של הקורס, מוכנות לכל מבחן ולוח שבועי - ולדעת מה באמת ידוע לך.">
    <meta property="og:image" content="{{BASE}}/og-image.png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:url" content="{{BASE}}/app/">
    <meta name="twitter:card" content="summary_large_image">'''


def add_head_tags(html, name, tags):
    """Web-only <head> tags, right after <meta charset>."""
    m = re.search(r'<meta charset="[^"]*">', html, flags=re.I)
    if not m:
        fail(f'{name}: no <meta charset> found')
    nl = '\r\n' if '\r\n' in html else '\n'
    return html[:m.end()] + nl + '    ' + tags.replace('\n', nl) + html[m.end():]


def add_header(html):
    return re.sub(r'(<!DOCTYPE html>\s*)', lambda m: m.group(1) + HEADER + '\n', html, count=1, flags=re.I)


def main():
    if not (CLIENT / 'renderer.js').exists():
        fail(f'desktop app not found at {CLIENT}')
    if not (SRC / 'web-shim.js').exists():
        fail('web-src/web-shim.js is missing')

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir()

    for name in COPY:
        src = CLIENT / name
        if not src.exists():
            fail(f'{name} is missing in {CLIENT}')
        shutil.copyfile(src, OUT / name)
    for name in OPTIONAL:
        src = CLIENT / name
        if src.is_dir():
            shutil.copytree(src, OUT / name)
        elif src.exists():
            shutil.copyfile(src, OUT / name)
    for src in SRC.iterdir():
        if src.is_file():
            shutil.copyfile(src, OUT / src.name)
        elif src.is_dir():   # web-src/assets: icons, manifest, preview image (served at the site root)
            shutil.copytree(src, OUT / src.name)

    # index.html: shim first, then the web page's icons / install / link
    # preview tags ({{BASE}} is filled in by server.js).
    index = read(OUT / 'index.html')
    # KaTeX from the server: its stylesheet, and a <script> before math.js
    # (the desktop app require()s it from node_modules).
    index, n = re.subn(r'node_modules/katex/dist/', 'vendor/katex/', index)
    if n == 0:
        fail('index.html: the KaTeX stylesheet link was not found')
    index, n = re.subn(r'(<script src="math\.js")', r'<script src="vendor/katex/katex.min.js" defer></script>\n    \1', index, count=1)
    if n == 0:
        fail('index.html: could not add the KaTeX script before math.js')
    index = add_header(add_shim(index, 'index.html'))
    index = add_head_tags(index, 'index.html', WEB_HEAD)
    write(OUT / 'index.html', index)

    # summary.html: shim first + KaTeX from the server.
    summary = read(OUT / 'summary.html')
    summary, n = re.subn(r'node_modules/katex/dist/', 'vendor/katex/', summary)
    if n == 0:
        fail('summary.html: the KaTeX stylesheet link was not found')
    if 'vendor/katex/katex.min.js' not in summary:
        # The desktop app require()s KaTeX from node_modules; the browser needs a <script>.
        summary = summary.replace('<script src="summary.js"></script>',
                                  '<script src="vendor/katex/katex.min.js"></script>\n    <script src="summary.js"></script>', 1)
        if 'vendor/katex/katex.min.js' not in summary:
            fail('summary.html: could not add the KaTeX script')
    summary = add_header(add_shim(summary, 'summary.html'))
    summary = add_head_tags(summary, 'summary.html', ICON_HEAD)
    write(OUT / 'summary.html', summary)

    # Every file a page refers to must exist in web/ (a missed file would be a
    # silent 404 in the browser).
    for page in ('index.html', 'summary.html'):
        for ref in re.findall(r'(?:src|href)="([^"#:?]+)"', read(OUT / page)):
            if ref.startswith(('vendor/', '/', 'http')):
                continue
            if not (OUT / ref).exists():
                fail(f'{page} refers to {ref}, which is not in web/')

    files = sorted(p.name for p in OUT.iterdir())
    print(f'sync-web: {len(files)} files from {CLIENT} -> {OUT}')


if __name__ == '__main__':
    main()
